ALTER TABLE users
  ADD COLUMN name VARCHAR(255) NOT NULL DEFAULT '' AFTER email,
  ADD COLUMN google_id VARCHAR(255) NULL AFTER name,
  ADD COLUMN role ENUM('admin','user') NOT NULL DEFAULT 'user' AFTER google_id,
  ADD COLUMN updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
